rubyprograms/chartingapp2/config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  resources :sales
  resources :purchases
  resources :suppliers
  resources :customers
  resources :product_descriptions
  resources :products

end

rubyprograms/chartingapp2/app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :product
  belongs_to :customer

  def price
    price_in_cents.to_f / 100 || read_attribute(:price)
  end

  def price=(p)
    write_attribute(:price_in_cents, p.to_f.round(2) * 100)
  end

  def revenue
    price * units_sold
  end
  
end

rubyprograms/chartingapp2/app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:price_in_cents, :units_sold, :product_id, :customer_id)
    end
end

rubyprograms/chartingapp2/app/helpers/sales_helper.rb
module SalesHelper
end

rubyprograms/chartingapp2/app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price_in_cents %><br>
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="field">
    <%= f.label :units_sold %><br>
    <%= f.number_field :units_sold %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.text_field :customer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rubyprograms/chartingapp2/app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

rubyprograms/chartingapp2/app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Price in cents</th>
      <th>Units sold</th>
      <th>Product</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.price_in_cents %></td>
        <td><%= sale.units_sold %></td>
        <td><%= sale.product %></td>
        <td><%= sale.customer %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

rubyprograms/chartingapp2/app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

rubyprograms/chartingapp2/app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price in cents:</strong>
  <%= @sale.price_in_cents %>
</p>

<p>
  <strong>Units sold:</strong>
  <%= @sale.units_sold %>
</p>

<p>
  <strong>Product:</strong>
  <%= @sale.product %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @sale.customer %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>